// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace addressbook_web_test
{ 
[TestFixture]
public class NewgroupTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void Newgroup()
    {
        OpenHomePage();
        Login("admin", "secret");
        GoToGroupsPage();
        InitGroupCreation();
        GroupFormData group = new GroupFormData("new");
            group.Footer = "123";
        FillGroupForm(group);
        SubmitGroupCreation();
        ReturnToGroupsPage();
        Logout();
    }
        
    private void Logout()
    {
        driver.FindElement(By.LinkText("Logout")).Click();
    }

    private void ReturnToGroupsPage()
    {
        driver.FindElement(By.LinkText("group page")).Click();
    }

    private void SubmitGroupCreation()
    {
        driver.FindElement(By.Name("submit")).Click();
    }

    private void FillGroupForm(GroupFormData group)
    {
        driver.FindElement(By.Name("group_name")).Click();
        driver.FindElement(By.Name("group_name")).SendKeys(group.Name);
        driver.FindElement(By.Name("group_header")).Click();
        driver.FindElement(By.Name("group_header")).SendKeys(group.Header);
        driver.FindElement(By.Name("group_footer")).Click();
        driver.FindElement(By.Name("group_footer")).SendKeys(group.Footer);
    }

    private void InitGroupCreation()
    {
        driver.FindElement(By.Name("new")).Click();
    }

    private void GoToGroupsPage()
    {
        driver.FindElement(By.LinkText("groups")).Click();
    }

    private void Login(string username, string password)
    {
        driver.Manage().Window.Size = new System.Drawing.Size(758, 984);
        driver.FindElement(By.Name("user")).SendKeys(username);
        driver.FindElement(By.Name("pass")).SendKeys(password);
        driver.FindElement(By.CssSelector("input:nth-child(7)")).Click();
    }

    private void OpenHomePage()
    {
        driver.Navigate().GoToUrl("http://localhost/addressbook/");
    }
}
}